<?php

namespace Tests\Inbionova;

use App\Models\User;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class NavigationTest extends TestCase
{
    private $usuario;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->usuario = User::factory()->create();
        Sanctum::actingAs(
            $this->usuario,
            ['*']
        );
    }

    public function test_administracion()
    {
        $response = $this->get('/administracion');
        $response->assertOk();
    }

    public function test_usuarios()
    {
        $response = $this->get(route('usuarios.edit', $this->usuario));
        $response->assertOk();

        $response = $this->get(route('usuarios'));
        $response->assertOk();

        $response = $this->get(route('usuarios.create'));
        $response->assertOk();

        $response = $this->get(route('usuarios.store'));
        $response->assertOk();
    }

    public function test_blog()
    {
        $response = $this->get(route('blog'));
        $response->assertOk();

        $response = $this->get(route('blog.create'));
        $response->assertOk();

        $response = $this->get(route('blog.store'));
        $response->assertOk();
    }

    public function test_categorias_blog()
    {
        $response = $this->get(route('blog-category'));
        $response->assertOk();

        $response = $this->get(route('blog-category.store'));
        $response->assertOk();
    }

    public function test_categorias_producto()
    {
        $response = $this->get(route('product-category'));
        $response->assertOk();

        $response = $this->get(route('product-category.store'));
        $response->assertOk();
    }

    public function test_productos()
    {
        $response = $this->get(route('producto'));
        $response->assertOk();

        $response = $this->get(route('producto.create'));
        $response->assertOk();

        $response = $this->get(route('producto.store'));
        $response->assertOk();
    }

    public function test_categoria_alimentos()
    {
        $response = $this->get(route('categoria-alimentos'));
        $response->assertOk();

        $response = $this->get(route('categoria-alimentos.create'));
        $response->assertOk();

        $response = $this->get(route('categoria-alimentos.store'));
        $response->assertOk();
    }

    public function test_alimentos()
    {
        $response = $this->get(route('alimentos'));
        $response->assertOk();

        $response = $this->get(route('alimentos.create'));
        $response->assertOk();

        $response = $this->get(route('alimentos.store'));
        $response->assertOk();
    }

    public function test_planes()
    {
        $response = $this->get(route('planes'));
        $response->assertOk();

        $response = $this->get(route('planes.create'));
        $response->assertOk();

        $response = $this->get(route('planes.store'));
        $response->assertOk();
    }

    public function test_preguntas()
    {
        $response = $this->get(route('preguntas'));
        $response->assertOk();

        $response = $this->get(route('preguntas.create'));
        $response->assertOk();

        $response = $this->get(route('preguntas.store'));
        $response->assertOk();
    }

    public function test_recetas()
    {
        $response = $this->get(route('recetas'));
        $response->assertOk();

        $response = $this->get(route('recetas.create'));
        $response->assertOk();

        $response = $this->get(route('recetas.store'));
        $response->assertOk();
    }

    public function test_ingredientes()
    {
        $response = $this->get(route('ingredientes'));
        $response->assertOk();

        $response = $this->get(route('ingredientes.create'));
        $response->assertOk();

        $response = $this->get(route('ingredientes.store'));
        $response->assertOk();
    }
}
