deploy:
  script:
    - apt-get update
    - apt-get -qq install git-ftp
    - git config git-ftp.url "$HOST"
    - git config git-ftp.user "$USERNAME"
    - git config git-ftp.password "$PASSWORD"
    - git ftp push
  only:
    - master
