<?php

namespace Tests\Feature;

use App\Models\Alimento;
use App\Models\CategoriaAlimento;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class AlimentoModuleTest extends TestCase
{

    // para que se borre la base de datos antes de cada test
    use RefreshDatabase;

    private $usuario;
    private $categoria_alimento;
    private $alimento;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->usuario = User::factory()->create();
        $this->categoria_alimento = CategoriaAlimento::factory()->create();

        // Aca se crea una categorias, y podemos controlar los datos creados
        $this->alimento = Alimento::factory([
            'id'=>1,
            'nombre'=>'Prueba',
            'categoria_alimento_id' => $this->categoria_alimento->id,
            'created_at'=>now(),
            'updated_at'=>now(),
        ])->create();

        Sanctum::actingAs(
            $this->usuario,
            ['*']
        );
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_alimentos_status()
    {
        $this->withoutExceptionHandling();
        $response = $this->get(route('alimentos'));
        $response->assertStatus(200);
    }

    public function test_create_alimentos()
    {
        $this->withoutExceptionHandling();
        $response = $this->get(route('alimentos.create'));
        $response->assertStatus(200);
    }

    public function test_edit_alimentos()
    {
        $this->withoutExceptionHandling();
        $response = $this->get(route('alimentos.edit', 1));
        $response->assertStatus(200);
    }

    public function test_list_alimentos()
    {

        $this->withoutExceptionHandling();

        $response = $this->get(route('alimentos'));

        $response->assertStatus(200);

        $response->assertViewIs('livewire.admin.alimentos.alimentos');
    }

    public function test_post_alimentos()
    {
        $this->WithoutMiddleware();
        $this->withoutExceptionHandling();
        $response = $this->post(route('alimentos.store'), [
            'nombre' => 'Test alimento',
            'categoria_alimento_id' => $this->categoria_alimento->id,
            'create_at' => now(),
            'update_at' => now(),
        ]);
        
        $response->assertStatus(302);

        // Acá deben haber 2 la creada en el setup y la agregada en post
        $this->assertCount(2, Alimento::all());

        $alimento = Alimento::all()->last();

        $this->assertEquals($alimento->nombre, 'Test alimento');
    }

    public function test_update_alimentos()
    {

        $response = $this->put(route('alimentos.update', $this->alimento), [
            // el parametro es el del name del formulario, por eso no te funcionaba con solamente nombre
            'nombre' => 'Test nombre',
        ]);

        $response->assertStatus(302);

        // Acá deben haber 2 la creada en el setup y la agregada en post
        $this->assertCount(1, Alimento::all());

        // Acá revisamos el primer registro agregado y modificado
        $alimento = Alimento::find(1);

        $this->assertEquals($alimento->nombre, 'Test nombre');
    }

    public function test_delete_alimentos()
    {
        $response = $this->delete(route('alimentos.delete', $this->alimento->id));

        $response->assertStatus(302);

        $this->assertCount(0, Alimento::all());
    }
}
