<?php

namespace Tests\Feature;

use App\Models\Alimento;
use App\Models\Ingrediente;
use App\Models\Receta;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class IngredienteModuleTest extends TestCase
{
    use RefreshDatabase;

    private $usuario;
    private $ingredientes;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->usuario = User::factory()->create();


        $this->recetas = Receta::factory()->create();

        $this->alimentos = Alimento::factory()->create();

        // Aca se crea una categorias, y podemos controlar los datos creados
        $this->ingredientes = Ingrediente::factory([
            'id'=>1,
            'porcion' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit.',
            'receta_id' => $this->recetas->id,
            'alimento_id' => $this->alimentos->id,
            'updated_at' => now(),
            'created_at' => now(),
        ])->create();

        Sanctum::actingAs(
            $this->usuario,
            ['*']
        );
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_ingredientes_status()
    {
        $response = $this->get(route('ingredientes.index',$this->recetas->id));

        $response->assertStatus(200);
    }

    public function test_edit_ingredientes()
    {
        $this->withoutExceptionHandling();
        $response = $this->get(route('ingredientes.edit', 1));
        $response->assertStatus(200);
    }

    public function test_list_ingredientes()
    {

        $this->withoutExceptionHandling();

        $response = $this->get(route('ingredientes.index',$this->recetas->id));

        $response->assertStatus(200);

        $response->assertViewIs('livewire.admin.ingredientes.ingredientes');
    }


    public function test_post_ingredientes()
    {
        $this->WithoutMiddleware();
        $this->withoutExceptionHandling();

        $response = $this->post(route('ingredientes.store'), [
            'id'=>1,
            'porcion' => 'Lorem, ipsum dolor sit amet consectetur adipisicing elit.',
            'receta_id' => $this->recetas->id,
            'alimento_id' => $this->alimentos->id,
            'updated_at' => now(),
            'created_at' => now(),
        ]);

        $response->assertStatus(302);

        // Acá deben haber 2 la creada en el setup y la agregada en post
        $this->assertCount(2, Ingrediente::all());

        $ingrediente = Ingrediente::all()->last();

        $this->assertEquals($ingrediente->porcion, 'Lorem, ipsum dolor sit amet consectetur adipisicing elit.');
    }

    public function test_update_ingredientes()
    {

        $response = $this->put(route('ingredientes.update', $this->ingredientes), [
            'porcion' => 'Test ingredientes',
            'receta_id' => $this->recetas->id,
            'alimento_id' => $this->alimentos->id,
        ]);

        $response->assertStatus(302);

        // Acá deben haber 2 la creada en el setup y la agregada en post
        $this->assertCount(1, Ingrediente::all());

        // Acá revisamos el primer registro agregado y modificado
        $ingrediente = Ingrediente::find(1);

        $this->assertEquals($ingrediente->porcion, 'Test ingredientes');
    }

    public function test_delete_ingredientes()
    {
        // dd(route('ingredientes.delete',$this->ingredientes->id));
        $response = $this->delete(route('ingredientes.delete',$this->ingredientes->id));

        $response->assertStatus(302);

        $this->assertCount(0, Ingrediente::all());
    }
}
