<?php

namespace Tests\Feature;

use App\Models\Pregunta;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class PreguntaModuleTest extends TestCase
{

    use RefreshDatabase;

    private $usuario;
    private $preguntas;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->usuario = User::factory()->create();

        
        $this->preguntas = Pregunta::factory([
            'id'=>1,
            'pregunta' => 'titulo',
            'icono' =>'placeholder.png',
            'descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet iure, officiis adipisci, illo perspiciatis harum obcaecati, inventore minus velit natus debitis. Accusamus ea nesciunt dolorem incidunt accusantium recusandae atque alias!',
            'tipo_respuestas' => '1',
            'updated_at' => now(),
            'created_at' => now(),
        ])->create();

        Sanctum::actingAs(
            $this->usuario,
            ['*']
        );
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_preguntas_status()
    {
        $response = $this->get(route('preguntas'));

        $response->assertStatus(200);
    }


    public function test_edit_preguntas()
    {
        $this->withoutExceptionHandling();
        $response = $this->get(route('preguntas.edit', 1));
        $response->assertStatus(200);
    }

    public function test_list_preguntas()
    {

        $this->withoutExceptionHandling();

        $response = $this->get(route('preguntas'));

        $response->assertStatus(200);

        $response->assertViewIs('livewire.admin.preguntas.preguntas');
    }


    public function test_post_preguntas()
    {
        $this->WithoutMiddleware();
        $this->withoutExceptionHandling();

        $response = $this->post(route('preguntas.store'), [
            'pregunta' => 'Test nombre',
            'icono' =>'placeholder.png',
            'descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet iure, officiis adipisci, illo perspiciatis harum obcaecati, inventore minus velit natus debitis. Accusamus ea nesciunt dolorem incidunt accusantium recusandae atque alias!',
            'tipo_respuestas' => '1',
            'updated_at' => now(),
            'created_at' => now(),
        ]);

        $response->assertStatus(302);

       
        $this->assertCount(2, Pregunta::all());

        $preguntas = Pregunta::all()->last();

        $this->assertEquals($preguntas->pregunta, 'Test nombre');
    }

    public function test_update_preguntas()
    {

        $response = $this->put(route('preguntas.update', $this->preguntas->id), [
            
            'pregunta' => 'Test pregunta',
            'icono' =>'placeholder.png',
            'descripcion' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet iure, officiis adipisci, illo perspiciatis harum obcaecati, inventore minus velit natus debitis. Accusamus ea nesciunt dolorem incidunt accusantium recusandae atque alias!',
            'tipo_respuestas' => '1',
            'updated_at' => now(),
            'created_at' => now(),
        ]);

        $response->assertStatus(302);

        
        $this->assertCount(1, Pregunta::all());

        
        $preguntas = Pregunta::find(1);

        $this->assertEquals($preguntas->pregunta, 'Test pregunta');
    }

    public function test_delete_preguntas()
    {

        $response = $this->delete(route('preguntas.delete', $this->preguntas->id));

        $response->assertStatus(302);

        $this->assertCount(0, Pregunta::all());
    }
}
